# Generated by Django 5.2.5 on 2025-08-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
