# Generated by Django 5.2.4 on 2025-08-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True),
        ),
    ]
